### ISSUE TITLE
Setting locale doesn't work

### ISSUE THREAD

**Issue by metz0r** [wedgex/ember-bootstrap-daterange#1]
Seems like bootstrap-daterangepicker sets it at initialization? Maybe the issue is on their side, it doesn't seem to update the locale when using setOptions.

**Comment by wedgex** [comment]
It looks like the value is being set correctly in `$('#daterange').data('daterangepicker').locale` but it's not updating the labels. I'll have to dig in and see if there's something special that needs to be done to re-render the labels.

**Comment by metz0r** [comment]
Did you find out what was wrong here? or should I take a look?

**Comment by wedgex** [comment]
No I haven't had much luck digging into it. Go for it.

**Comment by metz0r** [comment]
As I suspected this is an issue on bootstrap-daterangepicker's end, I'll keep my eyes on this issue: 
https://github.com/dangrossman/bootstrap-daterangepicker/issues/602
