### ISSUE TITLE
Start and End calendar divs not arranged in correct order

### ISSUE THREAD

**Issue by malchak** [wedgex/ember-bootstrap-daterange#3]
First of all, thanks for creating this addon!  You've done a really nice job.

I have found one issue that I'm hoping you can lend some insight into.  Whenever this component renders, it seems that the calendar containers are arranged in the opposite order, with the end date calendar rendered left of the start date calendar, but with the class name of "right".

![screen shot 2015-04-22 at 3 38 06 pm](https://cloud.githubusercontent.com/assets/1450296/7287075/3f969906-e906-11e4-9fbf-897d08407126.png)

For comparison, here is the markup from the [bootstrap date range picker plugin](http://www.daterangepicker.com/#ex5) showing the expected behavior.

![screen shot 2015-04-22 at 3 54 43 pm](https://cloud.githubusercontent.com/assets/1450296/7287286/fe339ec6-e907-11e4-8100-f6bc2bc8cd6a.png)

I'm not quite sure why this is happening, and am curious to know if you're experiencing the same.

**Comment by wedgex** [comment]
Sorry it took so long for me to get to this. I pulled down a copy of the dateranger picker and started playing around with it outside of the component and could reproduce this there too, so I think there might be a bug in the original lib. In fact on second inspection I just noticed some of the examples on the sample page do it as well http://www.daterangepicker.com/#ex4

It might be worth opening an issue over there https://github.com/dangrossman/bootstrap-daterangepicker
